s  =set()
n = input("Enter a number1: ")
s.add(int(n))
n = input("Enter a number2: ")
s.add(int(n))
n = input("Enter a number3: ")
s.add(int(n))
n = input("Enter a number4: ")
s.add(int(n))
n = input("Enter a number5: ")
s.add(int(n))
n = input("Enter a number6: ")
s.add(int(n))
n = input("Enter a number7: ")
s.add(int(n))
n = input("Enter a number8: ")
s.add(int(n))

print("Sum of all numbers in the set: ", sum(s))
